# **completed:**

1. Load data                    ✅
2. Target analysis              ✅
3. Customer analysis            ✅
4. Data types                   ✅
5. Categorical analysis         ✅
6. Missing-value analysis       ✅

# Identified factors
1. Dataset loading
2. Target analysis
3. Customer/observation analysis
4. Data-type analysis
5. D_63 / D_64 analysis
6. Full missing-value analysis
7. Missingness distribution
8. High/extreme missing-feature identification

In [43]:
# ==========================================
# PROJECT CONFIGURATION / CHECKPOINT
# ==========================================

from google.colab import drive
drive.mount('/content/drive')

import os
import pandas as pd
import numpy as np

# Main project folder
PROJECT_PATH = "/content/drive/MyDrive/AMEX_Credit_Risk_Capstone_Project"

# Project subfolders
RESULTS_PATH = os.path.join(PROJECT_PATH, "results")
TABLES_PATH = os.path.join(RESULTS_PATH, "tables")
FIGURES_PATH = os.path.join(RESULTS_PATH, "figures")

# Create folders if they don't already exist
os.makedirs(TABLES_PATH, exist_ok=True)
os.makedirs(FIGURES_PATH, exist_ok=True)

print("Project path:", PROJECT_PATH)
print("Tables path:", TABLES_PATH)
print("Figures path:", FIGURES_PATH)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Project path: /content/drive/MyDrive/AMEX_Credit_Risk_Capstone_Project
Tables path: /content/drive/MyDrive/AMEX_Credit_Risk_Capstone_Project/results/tables
Figures path: /content/drive/MyDrive/AMEX_Credit_Risk_Capstone_Project/results/figures

In [1]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [5]:
import os

PROJECT_PATH = "/content/drive/MyDrive/AMEX_Credit_Risk_Capstone_Project"

DATA_RAW = os.path.join(PROJECT_PATH, "data", "raw")
DATA_PROCESSED = os.path.join(PROJECT_PATH, "data", "processed")
NOTEBOOKS = os.path.join(PROJECT_PATH, "notebooks")
MODELS = os.path.join(PROJECT_PATH, "models")
RESULTS = os.path.join(PROJECT_PATH, "results")

print(PROJECT_PATH)

/content/drive/MyDrive/AMEX_Credit_Risk_Capstone_Project

In [6]:
os.listdir(PROJECT_PATH)

['notebooks', 'data', 'models', 'results', 'documentation']

In [8]:
import os
from getpass import getpass

os.environ["KAGGLE_API_TOKEN"] = getpass("Enter your Kaggle API token: ")

Enter your Kaggle API token: ··········

In [9]:
import kagglehub

print("KaggleHub authentication configured.")

KaggleHub authentication configured.

In [12]:
import kagglehub

kagglehub.login()

VBox(children=(HTML(value='<center> <img\nsrc=https://www.kaggle.com/static/images/site-logo.png\nalt=\'Kaggle…

Kaggle credentials set.
Kaggle credentials successfully validated.

In [13]:
print(kagglehub.whoami())

Kaggle credentials successfully validated.
{'username': 'achalajk'}

In [15]:


info = kagglehub.competition_download(
    "amex-default-prediction",
    output_dir="/content/drive/MyDrive/AMEX_Credit_Risk_Capstone_Project/data/raw"
)

print(info)

Downloading to /content/drive/MyDrive/AMEX_Credit_Risk_Capstone_Project/data/raw/amex-default-prediction.archive...

100%|██████████| 20.5G/20.5G [09:15<00:00, 39.6MB/s]

Extracting files...

/content/drive/MyDrive/AMEX_Credit_Risk_Capstone_Project/data/raw

In [17]:

raw_path = "/content/drive/MyDrive/AMEX_Credit_Risk_Capstone_Project/data/raw"

for root, dirs, files in os.walk(raw_path):
    for file in files:
        file_path = os.path.join(root, file)
        size_gb = os.path.getsize(file_path) / (1024**3)
        print(f"{file}: {size_gb:.2f} GB")

sample_submission.csv: 0.06 GB
test_data.csv: 31.50 GB
train_data.csv: 15.27 GB
train_labels.csv: 0.03 GB
bundle.complete: 0.00 GB

In [18]:
import pandas as pd

train_path = os.path.join(raw_path, "train_data.csv")
labels_path = os.path.join(raw_path, "train_labels.csv")

# Read only 5 rows — NOT the entire 15 GB file
train_sample = pd.read_csv(train_path, nrows=5)

print("Train sample shape:", train_sample.shape)

print("\nColumns:")
print(train_sample.columns.tolist())

print("\nSample data:")
display(train_sample)

Train sample shape: (5, 190)

Columns:
['customer_ID', 'S_2', 'P_2', 'D_39', 'B_1', 'B_2', 'R_1', 'S_3', 'D_41', 'B_3', 'D_42', 'D_43', 'D_44', 'B_4', 'D_45', 'B_5', 'R_2', 'D_46', 'D_47', 'D_48', 'D_49', 'B_6', 'B_7', 'B_8', 'D_50', 'D_51', 'B_9', 'R_3', 'D_52', 'P_3', 'B_10', 'D_53', 'S_5', 'B_11', 'S_6', 'D_54', 'R_4', 'S_7', 'B_12', 'S_8', 'D_55', 'D_56', 'B_13', 'R_5', 'D_58', 'S_9', 'B_14', 'D_59', 'D_60', 'D_61', 'B_15', 'S_11', 'D_62', 'D_63', 'D_64', 'D_65', 'B_16', 'B_17', 'B_18', 'B_19', 'D_66', 'B_20', 'D_68', 'S_12', 'R_6', 'S_13', 'B_21', 'D_69', 'B_22', 'D_70', 'D_71', 'D_72', 'S_15', 'B_23', 'D_73', 'P_4', 'D_74', 'D_75', 'D_76', 'B_24', 'R_7', 'D_77', 'B_25', 'B_26', 'D_78', 'D_79', 'R_8', 'R_9', 'S_16', 'D_80', 'R_10', 'R_11', 'B_27', 'D_81', 'D_82', 'S_17', 'R_12', 'B_28', 'R_13', 'D_83', 'R_14', 'R_15', 'D_84', 'R_16', 'B_29', 'B_30', 'S_18', 'D_86', 'D_87', 'R_17', 'R_18', 'D_88', 'B_31', 'S_19', 'R_19', 'B_32', 'S_20', 'R_20', 'R_21', 'B_33', 'D_89', 'R_22', 'R_23', 'D_91', 'D_92', 'D_93', 'D_94', 'R_24', 'R_25', 'D_96', 'S_22', 'S_23', 'S_24', 'S_25', 'S_26', 'D_102', 'D_103', 'D_104', 'D_105', 'D_106', 'D_107', 'B_36', 'B_37', 'R_26', 'R_27', 'B_38', 'D_108', 'D_109', 'D_110', 'D_111', 'B_39', 'D_112', 'B_40', 'S_27', 'D_113', 'D_114', 'D_115', 'D_116', 'D_117', 'D_118', 'D_119', 'D_120', 'D_121', 'D_122', 'D_123', 'D_124', 'D_125', 'D_126', 'D_127', 'D_128', 'D_129', 'B_41', 'B_42', 'D_130', 'D_131', 'D_132', 'D_133', 'R_28', 'D_134', 'D_135', 'D_136', 'D_137', 'D_138', 'D_139', 'D_140', 'D_141', 'D_142', 'D_143', 'D_144', 'D_145']

Sample data:

,customer_ID,S_2,P_2,D_39,B_1,B_2,R_1,S_3,D_41,B_3,...,D_136,D_137,D_138,D_139,D_140,D_141,D_142,D_143,D_144,D_145
0,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...,2017-03-09,0.938469,0.001733,0.008724,1.006838,0.009228,0.124035,0.008771,0.004709,...,NaN,NaN,NaN,0.002427,0.003706,0.003818,NaN,0.000569,0.000610,0.002674
1,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...,2017-04-07,0.936665,0.005775,0.004923,1.000653,0.006151,0.126750,0.000798,0.002714,...,NaN,NaN,NaN,0.003954,0.003167,0.005032,NaN,0.009576,0.005492,0.009217
2,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...,2017-05-28,0.954180,0.091505,0.021655,1.009672,0.006815,0.123977,0.007598,0.009423,...,NaN,NaN,NaN,0.003269,0.007329,0.000427,NaN,0.003429,0.006986,0.002603
3,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...,2017-06-13,0.960384,0.002455,0.013683,1.002700,0.001373,0.117169,0.000685,0.005531,...,NaN,NaN,NaN,0.006117,0.004516,0.003200,NaN,0.008419,0.006527,0.009600
4,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...,2017-07-16,0.947248,0.002483,0.015193,1.000727,0.007605,0.117325,0.004653,0.009312,...,NaN,NaN,NaN,0.003671,0.004946,0.008889,NaN,0.001670,0.008126,0.009827

In [20]:


labels_path = os.path.join(raw_path, "train_labels.csv")

labels = pd.read_csv(labels_path)

print("Shape:", labels.shape)

print("\nColumns:")
print(labels.columns.tolist())

print("\nFirst 10 rows:")
display(labels.head(10))

print("\nTarget distribution:")
print(labels.iloc[:, -1].value_counts())

print("\nTarget percentages:")
print(labels.iloc[:, -1].value_counts(normalize=True) * 100)

Shape: (458913, 2)

Columns:
['customer_ID', 'target']

First 10 rows:

                                         customer_ID  target
0  0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...       0
1  00000fd6641609c6ece5454664794f0340ad84dddce9a2...       0
2  00001b22f846c82c51f6e3958ccd81970162bae8b007e8...       0
3  000041bdba6ecadd89a52d11886e8eaaec9325906c9723...       0
4  00007889e4fcd2614b6cbe7f8f3d2e5c728eca32d9eb8a...       0
5  000084e5023181993c2e1b665ac88dbb1ce9ef621ec537...       0
6  000098081fde4fd64bc4d503a5d6f86a0aedc425c96f52...       0
7  0000d17a1447b25a01e42e1ac56b091bb7cbb06317be4c...       0
8  0000f99513770170a1aba690daeeb8a96da4a39f11fc27...       1
9  00013181a0c5fc8f1ea38cd2b90fe8ad2fa8cad9d9f13e...       1

Target distribution:
target
0    340085
1    118828
Name: count, dtype: int64

Target percentages:
target
0    74.106639
1    25.893361
Name: proportion, dtype: float64

In [21]:
# Read only customer_ID and date
customer_dates = pd.read_csv(
    train_path,
    usecols=["customer_ID", "S_2"]
)

customer_dates["S_2"] = pd.to_datetime(customer_dates["S_2"])

print("Total observations:", len(customer_dates))
print("Unique customers:", customer_dates["customer_ID"].nunique())

print("\nDate range:")
print(customer_dates["S_2"].min())
print(customer_dates["S_2"].max())

print("\nObservations per customer:")
print(customer_dates.groupby("customer_ID").size().describe())

Total observations: 5531451
Unique customers: 458913

Date range:
2017-03-01 00:00:00
2018-03-31 00:00:00

Observations per customer:
count    458913.000000
mean         12.053376
std           2.610273
min           1.000000
25%          13.000000
50%          13.000000
75%          13.000000
max          13.000000
dtype: float64

In [22]:
print("Train customers:", customer_dates["customer_ID"].nunique())
print("Label customers:", labels["customer_ID"].nunique())

print(
    "Customers in train but not labels:",
    len(set(customer_dates["customer_ID"]) - set(labels["customer_ID"]))
)

print(
    "Customers in labels but not train:",
    len(set(labels["customer_ID"]) - set(customer_dates["customer_ID"]))
)

Train customers: 458913
Label customers: 458913
Customers in train but not labels: 0
Customers in labels but not train: 0

In [23]:
obs_per_customer = customer_dates.groupby("customer_ID").size()

print(obs_per_customer.value_counts().sort_index())

1       5120
2       6098
3       5778
4       4673
5       4671
6       5515
7       5198
8       6110
9       6411
10      6721
11      5961
12     10623
13    386034
Name: count, dtype: int64

In [25]:
all_columns = pd.read_csv(
    train_path,
    nrows=0
).columns.tolist()

print("Total columns:", len(all_columns))

Total columns: 190

In [26]:
sample = pd.read_csv(
    train_path,
    nrows=10000
)

print(sample.dtypes.value_counts())

float64    185
object       4
int64        1
Name: count, dtype: int64

In [27]:
print("\nNon-numeric columns:")
print(
    sample.select_dtypes(exclude="number").columns.tolist()
)

Non-numeric columns:
['customer_ID', 'S_2', 'D_63', 'D_64']

In [28]:
# Identify numeric and categorical columns

numeric_cols = sample.select_dtypes(
    include=["number"]
).columns.tolist()

categorical_cols = sample.select_dtypes(
    exclude=["number"]
).columns.tolist()

print("Numeric columns:", len(numeric_cols))
print("Categorical/object columns:", len(categorical_cols))

print("\nCategorical columns:")
print(categorical_cols)

Numeric columns: 186
Categorical/object columns: 4

Categorical columns:
['customer_ID', 'S_2', 'D_63', 'D_64']

In [29]:
for col in ["D_63", "D_64"]:
    print("\n==============================")
    print(col)
    print("==============================")

    print(
        sample[col].value_counts(dropna=False)
    )

==============================
D_63
==============================
D_63
CO    7286
CR    1644
CL     969
XZ      65
XL      22
XM      14
Name: count, dtype: int64

==============================
D_64
==============================
D_64
O      5523
U      2719
R      1335
NaN     344
-1       79
Name: count, dtype: int64

In [30]:
print("D_63 unique values:")
print(sample["D_63"].unique())

print("\nD_64 unique values:")
print(sample["D_64"].unique())

D_63 unique values:
['CR' 'CO' 'CL' 'XZ' 'XM' 'XL']

D_64 unique values:
['O' 'R' nan 'U' '-1']

In [31]:
# All predictor columns
all_columns = pd.read_csv(
    train_path,
    nrows=0
).columns.tolist()

feature_columns = [
    col for col in all_columns
    if col not in ["customer_ID", "S_2"]
]

print("Predictor variables:", len(feature_columns))

Predictor variables: 188

In [32]:
missing_counts = pd.Series(
    0,
    index=feature_columns,
    dtype="int64"
)

total_rows = 0

for i, chunk in enumerate(
    pd.read_csv(
        train_path,
        usecols=feature_columns,
        chunksize=100000
    )
):

    missing_counts += chunk.isna().sum()
    total_rows += len(chunk)

    if (i + 1) % 10 == 0:
        print(
            f"Processed {total_rows:,} rows"
        )

missing_profile = pd.DataFrame({
    "feature": missing_counts.index,
    "missing_count": missing_counts.values,
})

missing_profile["missing_pct"] = (
    missing_profile["missing_count"]
    / total_rows
) * 100

missing_profile = missing_profile.sort_values(
    "missing_pct",
    ascending=False
)

print("\nTotal rows processed:", total_rows)

display(missing_profile.head(20))

Processed 1,000,000 rows
Processed 2,000,000 rows
Processed 3,000,000 rows
Processed 4,000,000 rows
Processed 5,000,000 rows

Total rows processed: 5531451

    feature  missing_count  missing_pct
106    D_87        5527586    99.930127
109    D_88        5525447    99.891457
144   D_108        5502513    99.476846
146   D_110        5500117    99.433530
147   D_111        5500117    99.433530
148    B_39        5497819    99.391986
72     D_73        5475595    98.990211
170    B_42        5459973    98.707789
179   D_137        5336752    96.480146
180   D_138        5336752    96.480146
177   D_135        5336752    96.480146
178   D_136        5336752    96.480146
176   D_134        5336752    96.480146
85      R_9        5218918    94.349891
102    B_29        5150035    93.104594
137   D_106        4990102    90.213255
173   D_132        4988874    90.191055
18     D_49        4985917    90.137597
141    R_26        4922146    88.984717
76     D_76        4908954    88.746226

In [33]:
missing_profile_path = os.path.join(
    PROJECT_PATH,
    "results",
    "tables",
    "missing_value_profile.csv"
)

missing_profile.to_csv(
    missing_profile_path,
    index=False
)

print("Saved:", missing_profile_path)

Saved: /content/drive/MyDrive/AMEX_Credit_Risk_Capstone_Project/results/tables/missing_value_profile.csv

In [34]:
print("Missing-value distribution:")

print(
    missing_profile["missing_pct"].describe()
)

Missing-value distribution:
count    188.000000
mean      15.468506
std       32.047613
min        0.000000
25%        0.000000
50%        0.178705
75%        3.231300
max       99.930127
Name: missing_pct, dtype: float64

In [35]:
thresholds = [50, 70, 80, 90, 95, 99]

for threshold in thresholds:
    count = (
        missing_profile["missing_pct"] >= threshold
    ).sum()

    print(
        f"Features with >= {threshold}% missing: {count}"
    )

Features with >= 50% missing: 30
Features with >= 70% missing: 25
Features with >= 80% missing: 23
Features with >= 90% missing: 18
Features with >= 95% missing: 13
Features with >= 99% missing: 6

In [36]:
print("\nFeatures with < 50% missing:")

display(
    missing_profile[
        missing_profile["missing_pct"] < 50
    ].tail(20)
)

Features with < 50% missing:

    feature  missing_count  missing_pct
101    R_16              0          0.0
104    S_18              0          0.0
105    D_86              0          0.0
107    R_17              0          0.0
96     R_13              0          0.0
93     S_17              0          0.0
99     R_15              0          0.0
71     B_23              0          0.0
68     D_71              0          0.0
62      R_6              0          0.0
61     S_12              0          0.0
64     B_21              0          0.0
63     S_13              0          0.0
124    D_94              0          0.0
126    R_25              0          0.0
127    D_96              0          0.0
139    B_36              0          0.0
125    R_24              0          0.0
166   D_127              0          0.0
175    R_28              0          0.0

In [37]:
missing_bins = pd.cut(
    missing_profile["missing_pct"],
    bins=[-0.01, 5, 20, 50, 80, 90, 100],
    labels=[
        "0-5%",
        "5-20%",
        "20-50%",
        "50-80%",
        "80-90%",
        "90-100%"
    ]
)

missing_summary = (
    missing_bins
    .value_counts()
    .sort_index()
)

print(missing_summary)

missing_pct
0-5%       148
5-20%        6
20-50%       4
50-80%       7
80-90%       5
90-100%     18
Name: count, dtype: int64

In [38]:
missing_summary_df = missing_summary.reset_index()

missing_summary_df.columns = [
    "missingness_range",
    "number_of_features"
]

display(missing_summary_df)

  missingness_range  number_of_features
0              0-5%                 148
1             5-20%                   6
2            20-50%                   4
3            50-80%                   7
4            80-90%                   5
5           90-100%                  18

In [39]:
extreme_missing = missing_profile[
    missing_profile["missing_pct"] >= 90
].copy()

display(
    extreme_missing[
        ["feature", "missing_count", "missing_pct"]
    ]
)

    feature  missing_count  missing_pct
106    D_87        5527586    99.930127
109    D_88        5525447    99.891457
144   D_108        5502513    99.476846
146   D_110        5500117    99.433530
147   D_111        5500117    99.433530
148    B_39        5497819    99.391986
72     D_73        5475595    98.990211
170    B_42        5459973    98.707789
179   D_137        5336752    96.480146
180   D_138        5336752    96.480146
177   D_135        5336752    96.480146
178   D_136        5336752    96.480146
176   D_134        5336752    96.480146
85      R_9        5218918    94.349891
102    B_29        5150035    93.104594
137   D_106        4990102    90.213255
173   D_132        4988874    90.191055
18     D_49        4985917    90.137597

In [40]:
high_missing = missing_profile[
    (missing_profile["missing_pct"] >= 50) &
    (missing_profile["missing_pct"] < 90)
].copy()

display(
    high_missing[
        ["feature", "missing_count", "missing_pct"]
    ]
)

    feature  missing_count  missing_pct
141    R_26        4922146    88.984717
76     D_76        4908954    88.746226
58     D_66        4908097    88.730733
8      D_42        4740137    85.694278
184   D_142        4587043    82.926577
29     D_53        4084585    73.842921
92     D_82        4058614    73.373406
22     D_50        3142402    56.809723
55     B_17        3137598    56.722874
136   D_105        3021431    54.622756
39     D_56        2990943    54.071581
43      S_9        2933643    53.035686

In [41]:
extreme_features_path = os.path.join(
    PROJECT_PATH,
    "results",
    "tables",
    "extreme_missing_features.csv"
)

extreme_missing[
    ["feature", "missing_count", "missing_pct"]
].to_csv(
    extreme_features_path,
    index=False
)

print("Saved:", extreme_features_path)

Saved: /content/drive/MyDrive/AMEX_Credit_Risk_Capstone_Project/results/tables/extreme_missing_features.csv

In [42]:
high_features_path = os.path.join(
    PROJECT_PATH,
    "results",
    "tables",
    "high_missing_features.csv"
)

high_missing[
    ["feature", "missing_count", "missing_pct"]
].to_csv(
    high_features_path,
    index=False
)

print("Saved:", high_features_path)

Saved: /content/drive/MyDrive/AMEX_Credit_Risk_Capstone_Project/results/tables/high_missing_features.csv